name: wsi_api_helper
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4
  - blosc=1.21.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - charls=2.2.0
  - click=8.0.0
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - cryptography=3.4.7
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2021.5.0
  - decorator=5.0.9
  - environs=9.3.2
  - freetype=2.10.4
  - fsspec=2021.5.0
  - giflib=5.2.1
  - idna=2.10
  - imagecodecs=2021.3.31
  - imageio=2.9.0
  - intel-openmp=2021.2.0
  - joblib=1.0.1
  - jpeg=9d
  - jxrlib=1.1
  - kiwisolver=1.3.1
  - lcms2=2.12
  - lerc=2.2.1
  - libaec=1.0.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.7
  - liblapack=3.9.0
  - libpng=1.6.37
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - libzopfli=1.0.3
  - locket=0.2.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - marshmallow=3.12.1
  - matplotlib-base=3.4.2
  - mkl=2021.2.0
  - msys2-conda-epoch=20160418
  - networkx=2.3
  - numpy=1.20.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.4
  - partd=1.2.0
  - pillow=8.1.2
  - pip=21.1.1
  - pooch=1.3.0
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.8.0
  - python-dateutil=2.8.1
  - python-dotenv=0.17.1
  - python_abi=3.8
  - pytz=2021.1
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - requests=2.25.1
  - scikit-image=0.18.1
  - scikit-learn=0.24.2
  - scipy=1.6.3
  - setuptools=49.6.0
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.35.5
  - tbb=2021.2.0
  - threadpoolctl=2.1.0
  - tifffile=2021.4.8
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - urllib3=1.26.4
  - vc=14.2
  - vs2015_runtime=14.28.29325
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - yaml=0.2.5
  - zfp=0.5.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
      - filecache==0.81
